describe('QAonCloud Website',function(){
    Cypress.on('uncaught:exception', (err, runnable) => {
        // You can check for specific errors here
        // If you want to ignore all uncaught exceptions, return false
        // This will not stop the test, even if an uncaught exception occurs
        return false;
      });

    it('Title',function(){
        cy.visit("https://www.qaoncloud.com")
        cy.title().should('eq','QA Testing Services | Software Testing Services - QAonCloud')
    })

    it('Navigating to the Headers and Dropdowns ',function(){
        cy.visit("https://www.qaoncloud.com")
        cy.get('.elementskit-menu-hamburger > :nth-child(3)').click()
        cy.get('#menu-item-319 > .ekit-menu-nav-link > .icon').click()
        cy.get('.elementor-element-4eceb4cb > .elementor-widget-container').click()
        cy.get('#navbarDropdown1').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .dropdown-menu > :nth-child(1) > :nth-child(1) > :nth-child(1) > .dropdown-item').click()
        cy.get('#navbarDropdown1').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .dropdown-menu > :nth-child(1) > :nth-child(1) > :nth-child(2) > .dropdown-item').click()
        cy.get('#navbarDropdown1').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .dropdown-menu > :nth-child(1) > .menu-border > :nth-child(1) > .dropdown-item').click()
        cy.get('#navbarDropdown2').click()
        cy.wait(2000)
        cy.get('#navbarDropdown3').click()
        cy.wait(2000)
        cy.get('#navbarDropdown4').click()
        cy.wait(2000)    
    })

    it('Navigating',function(){
        cy.visit("https://www.qaoncloud.com")
        cy.get('.elementskit-menu-hamburger > :nth-child(3)').click()
        cy.get('#menu-item-319 > .ekit-menu-nav-link > .icon').click()
        cy.get('.elementor-element-4eceb4cb > .elementor-widget-container').click()
        cy.get('#navbarDropdown4').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .dropdown-menu > :nth-child(1) > ul > :nth-child(1) > .dropdown-item').click()
        cy.wait(2000)
        cy.get('#navbarDropdown4').click()
        cy.get(':nth-child(4) > .dropdown-menu > :nth-child(1) > ul > :nth-child(2) > .dropdown-item').click()        
        cy.get('#navbarDropdown4').click()
        cy.get(':nth-child(4) > .dropdown-menu > :nth-child(1) > ul > :nth-child(3) > .dropdown-item').click()
        cy.wait(2000)
        cy.get('#navbarDropdown4').click()
        cy.get(':nth-child(4) > .dropdown-menu > :nth-child(1) > ul > :nth-child(4) > .dropdown-item').click()
        cy.wait(2000)
    })

    
    it('Contact US', function(){
        cy.visit("https://www.qaoncloud.com")
        cy.get(".elementor-button-text").click() //Contact US
        cy.get('form > [name="name"]').type('QA testing')
        cy.get('form > [name="email"]').type('qaengineer@qaoncloud.com ')
        cy.get('form > .onlyNumber').type('123234435454')
        cy.get('form > [name="companyname"]').type('QAonCloud')
        cy.get('form > [name="role"]').type('QA Engineer')
        cy.get('form > textarea.form-control').type('Test the applications that is developed by our dev steam')
        //cy.get('.recaptcha-checkbox-border').check().should('be.visible')
        cy.get('.contact-send > .btn').click()
    })

    it('Footer Tab',function(){
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.ekit-template-content-footer > .elementor > .elementor-top-section')
        cy.get('.elementor-element-b7925ff > .elementor-widget-container > .elementor-heading-title').click()
        cy.get('.elementor-element-6f23676 > .elementor-widget-container > .ekit-wid-con > .elementor-icon-list-items > :nth-child(1) > .elementor-repeater-item-01d06f0 > .ekit_page_list_content > .elementor-icon-list-text > .ekit_page_list_title_title').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(1) > .footer-list > :nth-child(3) > a').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(1) > .footer-list > :nth-child(4) > a').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(2) > .footer-list > :nth-child(2) > a').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(2) > .footer-list > :nth-child(3) > a').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(2) > .footer-list > :nth-child(4) > a').click()
        cy.scrollTo('bottom')
        cy.get(':nth-child(3) > .footer-list > li > a').click()
        cy.scrollTo('bottom')
        cy.get('[href="https://www.qaoncloud.com/privacy-policy"]').click()
        cy.scrollTo('bottom')
        cy.get('[href="https://www.qaoncloud.com/terms-of-use"]').click()
        cy.scrollTo('bottom')
    })

    it('Social Media',function(){
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.ekit-template-content-footer > .elementor > .elementor-top-section')
        cy.get('.twitter > .fasicon').click()
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.facebook').click()
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.linkedin > .fasicon').click()
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.Instagram').click()
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.whatsapp > .fab').click()
        cy.visit("https://www.qaoncloud.com")
        cy.scrollTo('bottom')
        cy.get('.youtube > .fab').click()
        cy.visit("https://www.qaoncloud.com")
    })
})